export const  TOAST_REQUEST = 'TOAST_REQUEST'
export const  TOAST_SUCCESS = 'TOAST_SUCCESS'
export const  TOAST_FAILED = 'TOAST_FAILED'

export const  USER_INITIAL_INPUT = 'USER_INITIAL_INPUT'

export const LOGGIN_USER_REQUEST =  'LOGGIN_USER_REQUEST'
export const LOGGIN_USER_SUCCESS =  'LOGGIN_USER_SUCCESS'
export const LOGGIN_USER_FAILED =  'LOGGIN_USER_FAILED'