export const TOAST_REQUEST = 'TOAST_REQUEST'
export const TOAST_SUCCESS = 'TOAST_SUCCESS'
export const TOAST_FAILED = 'TOAST_FAILED'

export const LOGGIN_USER_REQUEST = 'LOGGIN_USER_REQUEST'
export const LOGGIN_USER_SUCCESS = 'LOGGIN_USER_SUCCESS'
export const LOGGIN_USER_FAILED = 'LOGGIN_USER_FAILED'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const FETCH_USER_DETAILS_RQUEST = 'FETCH_USER_DETAILS_RQUEST'
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS'
export const FETCH_USER_DETAILS_FAILED = 'FETCH_USER_DETAILS_FAILED'

export const FETCH_PERSONALIZED_DATA_REQUEST = 'FETCH_PERSONALIZED_DATA_REQUEST'
export const FETCH_PERSONALIZED_DATA_SUCCESS = 'FETCH_PERSONALIZED_DATA_SUCCESS'
export const FETCH_PERSONALIZED_DATA_FAILED = 'FETCH_PERSONALIZED_DATA_FAILED'

export const SAVE_PERSONALIZED_DATA_REQUEST = 'SAVE_PERSONALIZED_DATA_REQUEST'
export const SAVE_PERSONALIZED_DATA_SUCCESS = 'SAVE_PERSONALIZED_DATA_SUCCESS'
export const SAVE_PERSONALIZED_DATA_FAILED = 'SAVE_PERSONALIZED_DATA_FAILED'

export const UDADATE_PERSONALIZED_DATA_REQUEST = 'UDADATE_PERSONALIZED_DATA_REQUEST'
export const UDADATE_PERSONALIZED_DATA_SUCCESS = 'UDADATE_PERSONALIZED_DATA_SUCCESS'
export const UDADATE_PERSONALIZED_DATA_FAILED = 'UDADATE_PERSONALIZED_DATA_FAILED'


export const FETCH_SUGGESSTION_BY_SEARCH_REQUEST = 'FETCH_SUGGESSTION_BY_SEARCH_REQUEST'
export const FETCH_SUGGESSTION_BY_SEARCH_SUCCESS = 'FETCH_SUGGESSTION_BY_SEARCH_SUCCESS'
export const FETCH_SUGGESSTION_BY_SEARCH_FAILED = 'FETCH_SUGGESSTION_BY_SEARCH_FAILED'

export const SELECTED_RECIPE_ID_OR_NAME = 'SELECTED_RECIPE_ID_OR_NAME'
export const SELECTED_RECIPE_ID_OR_NAME_SUCCESS = 'SELECTED_RECIPE_ID_OR_NAME_SUCCESS'
export const SELECTED_RECIPE_ID_OR_NAME_FAILED = 'SELECTED_RECIPE_ID_OR_NAME_FAILED'

export const FETCH_REICPE_DETAILS = 'FETCH_REICPE_DETAILS'
export const FETCH_REICPE_DETAILS_SUCCESS = 'FETCH_REICPE_DETAILS_SUCCESS'
export const FETCH_REICPE_DETAILS_FAILED = 'FETCH_REICPE_DETAILS_FAILED'

export const FETCH_REICPE_LISTING = 'FETCH_REICPE_DETAILS'
export const FETCH_REICPE_LISTING_SUCCESS = 'FETCH_REICPE_LISTING_SUCCESS'
export const FETCH_REICPE_LISTING_FAILED = 'FETCH_REICPE_LISTING_FAILED'

export const FETCH_REICPE_LISTING_BY_CATEGORY = 'FETCH_REICPE_LISTING_BY_CATEGORY'
export const FETCH_REICPE_LISTING_BY_CATEGORY_SUCCESS = 'FETCH_REICPE_LISTING_BY_CATEGORY_SUCCESS'
export const FETCH_REICPE_LISTING_BY_CATEGORY_FAILED = 'FETCH_REICPE_LISTING_BY_CATEGORY_FAILED'

//export const API_URL = "http://10.101.1.145:8000/api/"
export const API_URL = "https://foodiesrecipe.herokuapp.com/api/"
